app/api/urls.py
from django.urls import path

from . import views

app_name = "api"
urlpatterns = [
    path("docs/", view=views.DocumentationView.as_view(), name="docs"),
]

app/landing/urls.py
from django.urls import path

from . import views

app_name = "landing"
urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    path("start/", view=views.StartView.as_view(), name="start"),
]

app/projects/urls.py
from django.urls import path

from . import ajax_views, views

app_name = "projects"
urlpatterns = [
    path("", view=views.ListView.as_view(), name="list"),
    path("create/", view=views.CreateFormView.as_view(), name="form_create"),
    path("~modal/create/", views.ModalCreateFormView.as_view(), name="modal_form_create"),
    path("<uuid:pk>/", view=views.UpdateFormView.as_view(), name="form_update"),
    path("~modal/<uuid:pk>/", views.ModalUpdateFormView.as_view(), name="modal_form_update"),
    path("remove/<uuid:pk>/", view=views.RemoveView.as_view(), name="remove"),
    path("~set/<uuid:pk>/", view=ajax_views.SetActiveView.as_view(), name="set_active_project"),
]

app/research/urls.py
from django.urls import path

from . import ajax_views, views

app_name = "research"
urlpatterns = [
    # Project AJAX requests
    path("~timeline/<str:pk>/", ajax_views.TimelineListView.as_view(), name="timeline"),
    path("~summary/save/", ajax_views.SummarySaveView.as_view(), name="save_summary"),
    path("~summary/remove/<str:pk>/", ajax_views.SummaryRemoveView.as_view(), name="remove_summary"),
    path("~summary/<str:pk>/", ajax_views.SummaryView.as_view(), name="summary"),
    path("~note/save/", ajax_views.NoteSaveView.as_view(), name="save_note"),
    path("~note/remove/<str:pk>/", ajax_views.NoteRemoveView.as_view(), name="remove_note"),
    path("~note/<str:pk>/", ajax_views.NoteView.as_view(), name="note"),
    # Project research displays
    path("~modal/<str:pk>/", views.ModalPanelView.as_view(), name="panel_modal"),
    path("", views.PanelView.as_view(), name="panel"),
]

app/teams/urls.py
from django.urls import path

from . import ajax_views, views

app_name = "teams"
urlpatterns = [
    path("", view=views.ListView.as_view(), name="list"),
    path("create/", view=views.CreateFormView.as_view(), name="form_create"),
    path("update/<uuid:pk>/", view=views.UpdateFormView.as_view(), name="form_update"),
    path("remove/<uuid:pk>/", view=views.RemoveView.as_view(), name="remove"),
    path("<uuid:pk>/", view=views.MemberListView.as_view(), name="members"),
    path("members/remove/<uuid:pk>/", view=views.MemberRemoveView.as_view(), name="member_remove"),
    path("invites/remove/<uuid:pk>/", view=views.InviteRemoveView.as_view(), name="invite_remove"),
    path("invites/confirm/<uuid:pk>/", view=views.InviteConfirmView.as_view(), name="invite_confirm"),
    path("~invites/send/<uuid:team>/", view=ajax_views.InviteSendView.as_view(), name="invite_send"),
    path("~set/<uuid:pk>/", view=ajax_views.SetActiveView.as_view(), name="set_active_team"),
]

app/users/urls.py
from django.urls import path

from . import ajax_views, views

app_name = "users"
urlpatterns = [
    path("signup/", view=views.SignupFormView.as_view(), name="signup"),
    path("me/", view=views.DetailView.as_view(), name="me"),
    path("update/", view=views.UpdateFormView.as_view(), name="update"),
    path("token/", view=views.TokenFormView.as_view(), name="token"),
    path("token/embed", view=views.EmbeddedTokenFormView.as_view(), name="embed_token"),
    path("~token/generate", view=ajax_views.GenerateTokenView.as_view(), name="generate_token"),
    path("~token/revoke", view=ajax_views.RevokeTokenView.as_view(), name="revoke_token"),
    path("~redirect/", view=views.RedirectView.as_view(), name="redirect"),
    path("~settings/", view=ajax_views.SettingsView.as_view(), name="settings"),
    path("~settings/save", view=ajax_views.SaveSettingsView.as_view(), name="save_settings"),
]

app/landing/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.cache import never_cache
from django.views.generic import TemplateView


@method_decorator([never_cache], name="dispatch")
class HomeRedirectView(View):
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("research:panel")
        return redirect("users:signup")


class HomeView(TemplateView):
    template_name = "home.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("users:me")
        return super().dispatch(request, *args, **kwargs)


class StartView(LoginRequiredMixin, TemplateView):
    template_name = "getting_started.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


def Site404(request, exception=None):
    return HttpResponseRedirect("/")

app/landing/templates/getting_started.html
{% extends "base.html" %}

{% load static i18n %}

{% block title %}
  Getting Started
{% endblock title %}
{% block content %}
  <div id="getting-started-page" class="mt-5 pt-2">
    <div class="hero-banner d-flex justify-content-center mb-3">
      <div class="hero-banner-content row d-flex justify-content-center">
        <div class="hero-info col-md-9 text-center text-lg-start">
          <h1 class="display-6 fw-bold lh-1 mt-lg-5 mb-3 text-center">Getting Started with the Nexical Knowledge Explorer</h1>
          <hr />
          <p class="lead p-3">
            Nexical Core is an open AI platform that accelerates business productivity across your organization
            focused on data privacy, auditability and security, and research efficiency with your internal data and systems,
            while being cost effective and avoiding vendor lock-in.
          </p>
          <p class="lead p-3 text-center">
            <strong>You can get started with Nexical in 4 easy steps</strong>...
          </p>
        </div>
      </div>
    </div>
    <div class="how-to-step-wrapper">
      <div class="row card how-to-step teams-section">
        <h2 class="how-to-title">1. Create Teams</h2>
        <hr />
        <div class="row">
          <div class="col-md-9 how-to-text p-3">
            <p class="lead">The first step in using Nexical Knowledge Explorer is to set up one or more teams.</p>
            <div class="border p-3">
              <p>All documents, projects, and research material are accessible only to active team members.</p>
              <p>
                At any time you are active in a single team, which may be changed by selecting another team in the team selector at the top right of the page.
              </p>
            </div>
          </div>
          <div class="col-md-3 d-flex align-items-center">
            <a href="{% url 'teams:list' %}" class="how-to-link btn btn-primary mx-auto d-flex align-items-center"><i class="bx bx-caret-right-circle mx-auto"></i></a>
          </div>
        </div>
      </div>
      <div class="row card how-to-step libraries-section">
        <h2 class="how-to-title">2. Import Document Libraries</h2>
        <hr />
        <div class="row">
          <div class="col-md-9 how-to-text p-3">
            <p class="lead">The next step is to import business document libraries for use in integrated research activities.</p>
            <div class="border p-3">
              <p>When you upload documents to the Nexical engine they are processed and prepared for AI analysis over time.</p>
              <p>
                The core platform supports manual document uploads but bulk and automated imports can easily be added by our team.
              </p>
            </div>
          </div>
          <div class="col-md-3 d-flex align-items-center">
            <a href="{% url 'documents:list' %}" class="how-to-link btn btn-primary mx-auto d-flex align-items-center"><i class="bx bx-caret-right-circle mx-auto"></i></a>
          </div>
        </div>
      </div>
      <div class="row card how-to-step projects-section border">
        <h2 class="how-to-title">3. Manage Projects</h2>
        <hr />
        <div class="row">
          <div class="col-md-9 how-to-text p-3">
            <p class="lead">All AI research artifacts and human notes are grouped into projects.</p>
            <div class="border p-3">
              <p>Projects allow you to configure AI systems and link document libraries across all related research activities.</p>
              <p>Projects when combined with tag filtering can provide a simple and streamlined knowledge management system.</p>
            </div>
          </div>
          <div class="col-md-3 d-flex align-items-center">
            <a href="{% url 'projects:list' %}" class="how-to-link btn btn-primary mx-auto d-flex align-items-center"><i class="bx bx-caret-right-circle mx-auto"></i></a>
          </div>
        </div>
      </div>
    </div>
    <div class="how-to-research-wrapper mb-4">
      <div class="row card how-to-step research-section">
        <h2 class="how-to-title">4. Conduct Research</h2>
        <hr />
        <div class="row">
          <div class="col-md-9 how-to-text p-3">
            <p class="lead">Once we have a project we can start querying the referenced documents and taking notes.</p>
            <div class="border p-3">
              <p>
                Nexical Core seeks to combine human research and machine research into a common searchable knowledge base over time.
              </p>
              <p>
                As more AI generated artifacts and notes are added the AI incorporates that information for new research requests.
              </p>
              <p>
                AI generated artifacts and information and team notes can be tagged and easily filtered within the currently active project.
              </p>
            </div>
          </div>
          <div class="col-md-3 d-flex align-items-center">
            <a href="{% url 'research:panel' %}" class="how-to-link btn btn-primary mx-auto d-flex align-items-center"><i class="bx bx-caret-right-circle mx-auto"></i></a>
          </div>
        </div>
      </div>
    </div>
    <hr />
    <div class="row how-to-extra-wrapper mt-4">
      <div class="col-lg-6 row card how-to-step extra-step api-section">
        <h2 class="how-to-title">Interface with the API</h2>
        <hr />
        <div class="row mb-2">
          <div class="col-md-8 how-to-text p-3">
            <p class="lead">
              When you need more capabilities than our web interface or you need to integrate with external systems, you can build off our REST API.
            </p>
          </div>
          <div class="col-md-4 d-flex align-items-start">
            <a href="{% url 'api:docs' %}" class="how-to-link btn btn-primary mx-auto d-flex align-items-center"><i class="bx bx-caret-right-circle mx-auto"></i></a>
          </div>
        </div>
        <div class="border p-3">
          <p>
            All Nexical Knowledge Explorer data and capabilities can be accessed and performed through an easy to use OpenAPI compatible REST API.
          </p>
          <p>
            Our API is well documented and you can experiment with it through the Nexical Core Knowledge Explorer user interface.
          </p>
        </div>
      </div>
      <div class="col-lg-5 row card how-to-step extra-step account-section">
        <h2 class="how-to-title">Manage your Account</h2>
        <hr />
        <div class="row mb-2">
          <div class="col-md-7 how-to-text p-3">
            <p class="lead">You can easily edit your profile information, verified emails, passwords, and API tokens.</p>
          </div>
          <div class="col-md-5 d-flex align-items-start">
            <a href="{% url 'users:me' %}" class="how-to-link btn btn-primary mx-auto d-flex align-items-center"><i class="bx bx-caret-right-circle mx-auto"></i></a>
          </div>
        </div>
        <div class="border p-3">
          <p>
            When you need to modify anything relating to your user account you can find all user actions in the sidebar menu on the left.
          </p>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

app/landing/templates/home.html
{% extends "base.html" %}

{% load static i18n %}

{% block title %}
  Nexical Explorer
{% endblock title %}
{% block content %}
  <div id="public-home-page">
    <div class="hero-banner d-flex justify-content-center bg-black">
      <div class="hero-banner-content row d-flex justify-content-center">
        <div class="hero-info col-md-5 p-5 p-md-3 text-center text-lg-start">
          <h1 class="display-6 fw-bold lh-1 mt-lg-5 mb-3"></h1>
          <hr />
          <p class="lead p-3"></p>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}