app/api/urls.py
from django.urls import path

from . import views

app_name = "api"
urlpatterns = [
    path("docs/", view=views.DocumentationView.as_view(), name="docs"),
]

app/users/urls.py
from django.urls import path

from . import ajax_views, views

app_name = "users"
urlpatterns = [
    path("signup/", view=views.SignupFormView.as_view(), name="signup"),
    path("me/", view=views.DetailView.as_view(), name="me"),
    path("update/", view=views.UpdateFormView.as_view(), name="update"),
    path("token/", view=views.TokenFormView.as_view(), name="token"),
    path("token/embed", view=views.EmbeddedTokenFormView.as_view(), name="embed_token"),
    path("~token/generate", view=ajax_views.GenerateTokenView.as_view(), name="generate_token"),
    path("~token/revoke", view=ajax_views.RevokeTokenView.as_view(), name="revoke_token"),
    path("~redirect/", view=views.RedirectView.as_view(), name="redirect"),
    path("~settings/", view=ajax_views.SettingsView.as_view(), name="settings"),
    path("~settings/save", view=ajax_views.SaveSettingsView.as_view(), name="save_settings"),
]

app/users/models.py
import random
import string

from allauth.account.models import EmailAddress
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _
from timezone_field import TimeZoneField

from app.users.managers import UserManager
from app.utils import fields
from app.utils.models import BaseUUIDModel, BaseUUIDModelMixin


def get_user_by_email(email):
    user = User.objects.filter(email=email)
    return user[0] if user else None


def check_verified_email(email):
    addresses = EmailAddress.objects.filter(email=email, verified=True)
    return addresses[0].user if addresses else None


def generate_random_code():
    code = "".join(random.choices(string.ascii_uppercase + string.digits, k=6))
    try:
        UserInvite.objects.get(code=code)
    except UserInvite.DoesNotExist:
        pass
    return code


class User(BaseUUIDModelMixin, AbstractUser):
    username = None  # type: ignore
    email = models.EmailField(_("Email Address"), unique=True)
    timezone = TimeZoneField(_("Timezone"), choices_display="WITH_GMT_OFFSET", default="US/Eastern")

    first_name = models.CharField(_("First Name"), blank=False, max_length=255)
    last_name = models.CharField(_("Last Name"), blank=False, max_length=255)

    settings = fields.DictionaryField(_("User Settings"))

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    objects = UserManager()

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.email})"

    def check_member(self, *groups):
        return self.groups.filter(name__in=groups).exists()

    @property
    def emails(self):
        return list(EmailAddress.objects.filter(user=self).values_list("email", flat=True))

    @property
    def verified_emails(self):
        return list(EmailAddress.objects.filter(user=self, verified=True).values_list("email", flat=True))

    def export(self):
        return {
            "email": self.email,
            "first_name": self.first_name,
            "last_name": self.last_name,
            "timezone": str(self.timezone),
        }


class UserInvite(BaseUUIDModel):
    email = models.EmailField(_("Email Address"), unique=True)
    code = models.CharField(_("Invite Code"), blank=True, editable=False, default=generate_random_code)

    def __str__(self):
        return f"{self.email} [ {self.code} ]"

app/users/forms.py
from allauth.account.utils import send_email_confirmation
from django import forms
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import login
from django.contrib.auth.models import Group
from django.contrib.auth.password_validation import validate_password
from django.utils.translation import gettext_lazy as _

from app.teams.models import Team, get_active_team, set_active_team

from .models import User, UserInvite


class SignupForm(forms.Form):
    first_name = forms.CharField(label="First name", max_length=150)
    last_name = forms.CharField(label="Last name", max_length=150)

    email = forms.EmailField(label="Email address")
    password = forms.CharField(max_length=32, widget=forms.PasswordInput)
    confirm_password = forms.CharField(max_length=32, widget=forms.PasswordInput)

    invite_code = forms.CharField(
        label="Invite code",
        max_length=6,
        help_text="If you do not have an invite code <a href='/contact'>please contact us</a>",
    )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            User.objects.get(email=email)
            raise forms.ValidationError(
                "A user with this email already exists in the system.",
                code="user_exists",
            )
        except User.DoesNotExist:
            pass
        return email

    def clean_password(self):
        password = self.cleaned_data.get("password")
        validate_password(password)
        return password

    def clean_confirm_password(self):
        password = self.cleaned_data.get("password")
        confirm_password = self.cleaned_data.get("confirm_password")
        if password and password != confirm_password:
            raise forms.ValidationError("Your passwords do not match.", code="password_mismatch")
        return confirm_password

    def clean_invite_code(self):
        invite_code = self.cleaned_data.get("invite_code")
        error_message = "You must specify a valid invite code to sign up for this site"
        error_code = "invalid_invite_code"
        try:
            self.invite = UserInvite.objects.get(code=self.cleaned_data.get("invite_code"))
            if self.invite.email != self.cleaned_data.get("email"):
                raise forms.ValidationError(error_message, code=error_code)
        except UserInvite.DoesNotExist:
            raise forms.ValidationError(error_message, code=error_code)
        return invite_code

    def signup(self, request):
        user = User.objects.create_user(
            email=self.cleaned_data["email"],
            password=self.cleaned_data["password"],
            first_name=self.cleaned_data["first_name"],
            last_name=self.cleaned_data["last_name"],
            settings={},
        )
        user.groups.add(Group.objects.get(name="team_member"))
        user.save()

        (team, created) = Team.objects.get_or_create(owner=user, name="Personal")
        if not get_active_team(user):
            set_active_team(user, team.id)

        login(request, user, backend="django.contrib.auth.backends.ModelBackend")
        send_email_confirmation(request, user, True)

        self.invite.delete()
        return user


class AdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User
        field_classes = {"email": forms.EmailField}


class AdminCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        fields = ("email",)
        field_classes = {"email": forms.EmailField}
        error_messages = {
            "email": {"unique": _("This email has already been taken.")},
        }

app/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, TemplateView, UpdateView
from rest_framework.authtoken.models import Token

from app.utils.auth import PublicOnlyAccessMixin, TeamAccessMixin
from app.utils.models import render_field_table
from app.utils.views import ParamFormView

from . import forms, models


class SignupFormView(PublicOnlyAccessMixin, ParamFormView):
    template_name = "user_signup.html"
    form_class = forms.SignupForm

    def form_valid(self, form):
        self.object = form.signup(self.request)
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse("landing:start")


class DetailView(LoginRequiredMixin, DetailView):
    template_name = "user_detail.html"
    model = models.User

    def get_object(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["field_table"] = render_field_table(
            self.request.user,
            "email",
            "first_name",
            "last_name",
            "timezone",
            id="user-fields",
            classes="field-table",
        )
        return context


class UpdateFormView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    template_name = "user_form.html"
    model = models.User
    fields = ["first_name", "last_name", "timezone"]
    success_message = _("Information successfully updated")

    def get_object(self):
        return self.request.user

    def get_success_url(self, **kwargs):
        return reverse("users:me")


class BaseTokenFormView(TeamAccessMixin, TemplateView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context["token"] = Token.objects.get(user=self.request.user).key
        except Token.DoesNotExist:
            context["token"] = ""
        return context


class TokenFormView(BaseTokenFormView):
    template_name = "user_token.html"


class EmbeddedTokenFormView(BaseTokenFormView):
    template_name = "user_token_embed.html"


class RedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:me")

app/users/templates/user_detail.html
{% extends "base.html" %}

{% load static user_perms %}

{% block title %}
  Member: {{ object.first_name }} {{ object.last_name }}
{% endblock title %}
{% block content %}
  <div class="container-fluid">
    <div class="page-wrapper d-flex justify-content-center">
      {% if object == request.user %}
        {% is_team_member object as team_member %}
        <div class="container">
          <div class="row">
            <div class="col">
              <h1>Welcome {{ object.first_name }}!</h1>
            </div>
          </div>
          <div class="row mt-4">
            <div class="col-md-12">
              <div class="user-actions" role="group" aria-label="User Actions">
                <a class="btn group-btn align-middle btn-outline-primary mx-1 my-2 my-lg-0 d-block d-lg-inline active"
                   href="{% url 'users:me' %}"
                   role="button"><span>Account Home</span></a>
                <a class="btn group-btn align-middle btn-outline-primary mx-1 my-2 my-lg-0 d-block d-lg-inline"
                   href="{% url 'users:update' %}"
                   role="button"><span>Update
                Profile</span></a>
                <a class="btn group-btn align-middle btn-outline-primary mx-1 my-2 my-lg-0 d-block d-lg-inline"
                   href="{% url 'account_email' %}"
                   role="button"><span>Update
                E-Mails</span></a>
                <a class="btn group-btn align-middle btn-outline-primary mx-1 my-2 my-lg-0 d-block d-lg-inline"
                   href="{% url 'account_change_password' %}"
                   role="button"><span>Update
                Password</span></a>
                {% if team_member %}
                  <a class="btn group-btn align-middle btn-outline-primary mx-1 my-2 my-lg-0 d-block d-lg-inline"
                     href="{% url 'users:token' %}"
                     role="button"><span>Update
                  Token</span></a>
                {% endif %}
              </div>
            </div>
          </div>
          <div class="row mt-4">
            <div class="col">
              <div class="my-3 p-3 border rounded-4 bg-white">{{ field_table }}</div>
            </div>
          </div>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock content %}

app/users/templates/user_form.html
{% extends "base.html" %}

{% load crispy_forms_tags user_perms %}

{% block title %}
  Update: {{ user.first_name }} {{ user.last_name }}
{% endblock title %}
{% block content %}
  <div id="user-profile-form" class="container">
    <div class="page-wrapper d-flex justify-content-center">
      {% is_team_member object as team_member %}
      <div class="container">
        <div class="row">
          <div class="col">
            <h1>Welcome {{ object.first_name }}!</h1>
          </div>
        </div>
        <div class="row mt-4">
          <div class="col-md-12">
            <div class="user-actions" role="group" aria-label="User Actions">
              <a class="btn group-btn align-middle btn-outline-primary mx-1 my-2 my-lg-0 d-block d-lg-inline"
                 href="{% url 'users:me' %}"
                 role="button"><span>Account Home</span></a>
              <a class="btn group-btn align-middle btn-outline-primary mx-1 my-2 my-lg-0 d-block d-lg-inline active"
                 href="{% url 'users:update' %}"
                 role="button"><span>Update
              Profile</span></a>
              <a class="btn group-btn align-middle btn-outline-primary mx-1 my-2 my-lg-0 d-block d-lg-inline"
                 href="{% url 'account_email' %}"
                 role="button"><span>Update
              E-Mails</span></a>
              <a class="btn group-btn align-middle btn-outline-primary mx-1 my-2 my-lg-0 d-block d-lg-inline"
                 href="{% url 'account_change_password' %}"
                 role="button"><span>Update
              Password</span></a>
              {% if team_member %}
                <a class="btn group-btn align-middle btn-outline-primary mx-1 my-2 my-lg-0 d-block d-lg-inline"
                   href="{% url 'users:token' %}"
                   role="button"><span>Update
                Token</span></a>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="row mt-4">
          <div class="col">
            <div class="my-3 p-3 border rounded-4 bg-white">
              <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="form-buttons text-align-center">
                  <button type="submit" class="btn btn-primary mb-5">Update</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

app/users/templates/user_token.html
{% extends "base.html" %}

{% load static i18n site_urls crispy_forms_tags user_perms %}

{% block title %}
  Manage API Token: {{ user.first_name }} {{ user.last_name }}
{% endblock title %}
{% block javascript %}
  {{ block.super }}
  <script defer src="{% static 'js/user-token-page.min.js' %}"></script>
{% endblock javascript %}
{% block content %}
  <div id="user-token-form" class="container">
    <div class="page-wrapper d-flex justify-content-center">
      {% is_team_member request.user as team_member %}
      <div class="container">
        <div class="row">
          <div class="col">
            <h1>Welcome {{ request.user.first_name }}!</h1>
          </div>
        </div>
        <div class="row mt-4">
          <div class="col-md-12">
            <div class="user-actions" role="group" aria-label="User Actions">
              <a class="btn group-btn align-middle btn-outline-primary mx-1 my-2 my-lg-0 d-block d-lg-inline"
                 href="{% url 'users:me' %}"
                 role="button"><span>Account Home</span></a>
              <a class="btn group-btn align-middle btn-outline-primary mx-1 my-2 my-lg-0 d-block d-lg-inline"
                 href="{% url 'users:update' %}"
                 role="button"><span>Update
              Profile</span></a>
              <a class="btn group-btn align-middle btn-outline-primary mx-1 my-2 my-lg-0 d-block d-lg-inline"
                 href="{% url 'account_email' %}"
                 role="button"><span>Update
              E-Mails</span></a>
              <a class="btn group-btn align-middle btn-outline-primary mx-1 my-2 my-lg-0 d-block d-lg-inline"
                 href="{% url 'account_change_password' %}"
                 role="button"><span>Update
              Password</span></a>
              {% if team_member %}
                <a class="btn group-btn align-middle btn-outline-primary mx-1 my-2 my-lg-0 d-block d-lg-inline active"
                   href="{% url 'users:token' %}"
                   role="button"><span>Update
                Token</span></a>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="row mt-4">
          <div class="col my-3 p-5 border rounded-4 bg-white">
            <div class="api-docs">
              <a href="{% url 'api:docs' %}" class="api-doc-link">
                <i class="bx bx-cloud-download"></i>
                <span>{% translate 'API Documentation' %}</span>
              </a>
            </div>
            <div class="my-3 border rounded-4 p-md-3">
              {% if token %}
                <div class="api-token row border-bottom p-2 mb-3">
                  <div id="token-value" class="col-10 p-3 ">{{ token }}</div>
                  <div class="col-2 p-3">
                    <a id="token-copy" href="#" class="token-op text-decoration-none d-flex align-items-center gap-1" title="Copy">
                      <i class="bx bx-copy bx-sm"></i> <span>Copy</span>
                    </a>
                  </div>
                </div>
              {% else %}
                <div class="alert alert-warning d-flex flex-row gap-1">
                  <i class="bx bx-error"></i>
                  <div>
                    <strong>No Token registered in your account.</strong>
                    <p>Please click the "Generate Token" button.</p>
                  </div>
                </div>
              {% endif %}
              <div class="form-buttonsx">
                <button type="button" class="token-button btn btn-primary mb-5" data-url="{% url 'users:generate_token' %}">
                  {% if token %}
                    Regenerate Token
                  {% else %}
                    Generate Token
                  {% endif %}
                </button>
                {% if token %}
                  <button type="button" class="token-button btn btn-primary mb-5" data-url="{% url 'users:revoke_token' %}">
                    Revoke
                  </button>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

app/users/templates/user_token_embed.html
{% extends "base_min.html" %}

{% load static i18n site_urls crispy_forms_tags %}

{% block title %}
  Manage API Token: {{ user.first_name }} {{ user.last_name }}
{% endblock title %}
{% block javascript %}
  {{ block.super }}
  <script defer src="{% static 'js/user-token-page.min.js' %}"></script>
  <script src="{% static 'js/iframe-resizer-child-min.js' %}"></script>
{% endblock javascript %}
{% block feedback %}
{% endblock feedback %}
{% block content %}
  <div id="user-token-form" class="container">
    <div class="row bg-white rounded-5 page-wrapper d-flex justify-content-center">
      <div class="token-wrapper container">
        <h1>Manage my API Token</h1>
        <div class="api-docs">
          <a href="{% url 'api-docs' %}" class="api-doc-link">
            <i class="bx bx-cloud-download"></i>
            <span>{% translate 'API Documentation' %}</span>
          </a>
        </div>
        <div class="my-3 border rounded-4 p-md-3">
          {% if token %}
            <div class="api-token row border-bottom p-2 mb-3">
              <div id="token-value" class="col-10 p-3 ">{{ token }}</div>
              <div class="col-2 p-3">
                <a id="token-copy" href="#" class="token-op text-decoration-none d-flex align-items-center gap-1" title="Copy">
                  <i class="bx bx-copy bx-sm"></i> <span>Copy</span>
                </a>
              </div>
            </div>
          {% else %}
            <div class="alert alert-warning d-flex flex-row gap-1">
              <i class="bx bx-error"></i>
              <div>
                <strong>No Token registered in your account.</strong>
                <p>Please click the "Generate Token" button.</p>
              </div>
            </div>
          {% endif %}
          <div class="form-buttonsx">
            <button type="button" class="token-button btn btn-primary mb-5" data-url="{% url 'users:generate_token' %}">
              {% if token %}
                Regenerate Token
              {% else %}
                Generate Token
              {% endif %}
            </button>
            {% if token %}
              <button type="button" class="token-button btn btn-primary mb-5" data-url="{% url 'users:revoke_token' %}">
                Revoke
              </button>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}