app/api/urls.py
from django.urls import path

from . import views

app_name = "api"
urlpatterns = [
    path("docs/", view=views.DocumentationView.as_view(), name="docs"),
]

app/users/urls.py
from django.urls import path

from . import ajax_views, views

app_name = "users"
urlpatterns = [
    path("signup/", view=views.SignupFormView.as_view(), name="signup"),
    path("me/", view=views.DetailView.as_view(), name="me"),
    path("update/", view=views.UpdateFormView.as_view(), name="update"),
    path("token/", view=views.TokenFormView.as_view(), name="token"),
    path("token/embed", view=views.EmbeddedTokenFormView.as_view(), name="embed_token"),
    path("~token/generate", view=ajax_views.GenerateTokenView.as_view(), name="generate_token"),
    path("~token/revoke", view=ajax_views.RevokeTokenView.as_view(), name="revoke_token"),
    path("~redirect/", view=views.RedirectView.as_view(), name="redirect"),
    path("~settings/", view=ajax_views.SettingsView.as_view(), name="settings"),
    path("~settings/save", view=ajax_views.SaveSettingsView.as_view(), name="save_settings"),
]

app/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}
  Forbidden (403)
{% endblock title %}
{% block content %}
  <h1>Forbidden (403)</h1>
  <p>
    {% if exception %}
      {{ exception }}
    {% else %}
      You're not allowed to access this page.
    {% endif %}
  </p>
{% endblock content %}

app/templates/base.html
{% load static i18n %}

<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>
      {% block title %}
        Nexical Explorer
      {% endblock title %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Nexical Explorer" />
    <meta name="author" content="Nexical AI" />
    <link rel="icon" href="{% static 'images/icons/favicon.ico' %}" />
    {% block css %}
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
            crossorigin="anonymous" />
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
      <link rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css" />
      <link href="{% static 'css/project.min.css' %}" rel="stylesheet" />
    {% endblock css %}
    {% block javascript %}
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
              integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
              crossorigin="anonymous"></script>
      <script defer src="{% static 'js/project.min.js' %}"></script>
    {% endblock javascript %}
  </head>
  <body class="{% if request.user.is_authenticated %}loggedin{% else %}anonymous{% endif %}">
    <div class="overlay-mobile animate__animated__fast"></div>
    {% include 'components/header.html' %}
    {% include 'components/left_nav.html' %}
    <main>
      <div id="page-container">
        {% block wrapper %}
          <div id="page-content-wrapper" class="content-wrapper">
            <div id="main-content">
              {% include 'components/messages.html' %}
              {% block content %}
              {% endblock content %}
            </div>
          </div>
        {% endblock wrapper %}
      </div>
      <input type="hidden" id="csrf-token" value="{{ csrf_token }}" />
      <input type="hidden" id="user-settings-url" value="{% url 'users:settings' %}" />
      <input type="hidden" id="user-settings-save-url" value="{% url 'users:save_settings' %}" />
    </main>
    {% block modal %}
    {% endblock modal %}
    <div id="outer-help">
      {% if request.user.is_authenticated %}
        {% include 'components/help_bubble.html' %}
      {% endif %}
    </div>
    {% include 'components/footer.html' %}
    {% block inline_javascript %}
    {% endblock inline_javascript %}
    <script type="text/javascript" id="zsiqchat">
        var $zoho = $zoho || {};
        $zoho.salesiq = $zoho.salesiq || {
            widgetcode: "siqf02f51a8289b28c13b114f986a565a8db16550b78d3ba531b3bac079c1da4f3f",
            values: {},
            ready: function() {}
        };
        var d = document;
        s = d.createElement("script");
        s.type = "text/javascript";
        s.id = "zsiqscript";
        s.defer = true;
        s.src = "https://salesiq.zohopublic.com/widget";
        t = d.getElementsByTagName("script")[0];
        t.parentNode.insertBefore(s, t);
    </script>
    {% if request.user.is_authenticated %}
      <script>
          aa $zoho.salesiq.ready = function() {
              $zoho.salesiq.visitor.id("{{ request.user.id }}");
              $zoho.salesiq.visitor.email("{{ request.user.email }}");
              $zoho.salesiq.visitor.name("{{ request.user.first_name }} {{ request.user.last_name }}");
              $zoho.salesiq.visitor.info({
                  "organization": "{{ request.user.organization }}",
                  "position": "{{ request.user.position }}"
              });
          }
      </script>
    {% endif %}
  </body>
</html>

app/templates/base_min.html
{% load static i18n %}

<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>
      {% block title %}
        Nexical Explorer
      {% endblock title %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Nexical Explorer" />
    <meta name="author" content="Nexical AI" />
    <link rel="icon" href="{% static 'images/icons/favicon.ico' %}" />
    {% block css %}
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
            crossorigin="anonymous" />
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
      <link rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css" />
      <link href="{% static 'css/project.min.css' %}" rel="stylesheet" />
    {% endblock css %}
    {% block javascript %}
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
              integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
              crossorigin="anonymous"></script>
      <script defer src="{% static 'js/project.min.js' %}"></script>
    {% endblock javascript %}
  </head>
  <body>
    <div id="page-container">
      {% block wrapper %}
        <div id="page-content-wrapper" class="content-wrapper">
          <div id="main-content">
            {% include 'components/messages.html' %}
            {% block content %}
            {% endblock content %}
          </div>
        </div>
      {% endblock wrapper %}
      <input type="hidden" id="csrf-token" value="{{ csrf_token }}" />
      <input type="hidden" id="user-settings-url" value="{% url 'users:settings' %}" />
      <input type="hidden" id="user-settings-save-url" value="{% url 'users:save_settings' %}" />
    </div>
    {% block help %}
      {% if request.user.is_authenticated %}
        {% include 'components/help_bubble.html' %}
      {% endif %}
    {% endblock help %}
    {% block inline_javascript %}
    {% endblock inline_javascript %}
    <script type="text/javascript" id="zsiqchat">
        var $zoho = $zoho || {};
        $zoho.salesiq = $zoho.salesiq || {
            widgetcode: "siqf02f51a8289b28c13b114f986a565a8db16550b78d3ba531b3bac079c1da4f3f",
            values: {},
            ready: function() {}
        };
        var d = document;
        s = d.createElement("script");
        s.type = "text/javascript";
        s.id = "zsiqscript";
        s.defer = true;
        s.src = "https://salesiq.zohopublic.com/widget";
        t = d.getElementsByTagName("script")[0];
        t.parentNode.insertBefore(s, t);
    </script>
    {% if request.user.is_authenticated %}
      <script>
          $zoho.salesiq.ready = function() {
              $zoho.salesiq.visitor.id("{{ request.user.id }}");
              $zoho.salesiq.visitor.email("{{ request.user.email }}");
              $zoho.salesiq.visitor.name("{{ request.user.first_name }} {{ request.user.last_name }}");
              $zoho.salesiq.visitor.info({
                  "organization": "{{ request.user.organization }}",
                  "position": "{{ request.user.position }}"
              });
          }
      </script>
    {% endif %}
  </body>
</html>